// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ePayments.Tests.Web.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SignIn")]
    [NUnit.Framework.CategoryAttribute("SignIn")]
    public partial class SignInFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SignIn.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SignIn", null, ProgrammingLanguage.CSharp, new string[] {
                        "SignIn"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Капча при входе в систему")]
        [NUnit.Framework.CategoryAttribute("349996")]
        public virtual void КапчаПриВходеВСистему()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Капча при входе в систему", new string[] {
                        "349996"});
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
  testRunner.Given("User goes to SignIn page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.Given("User signin \"Epayments\" with \"nikitoz12@mail.ru\" password \"72621010Abaccc\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
  testRunner.Given("User gets \"Неверный логин или пароль\" message on Landing SignIn form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
     testRunner.Given("User type password \"72621010Abaccc\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 11
  testRunner.Given("User clicks on \"Войти\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 12
  testRunner.Given("User gets \"Неверный логин или пароль\" message on Landing SignIn form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 13
  testRunner.Given("Captcha appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 14
  testRunner.Then("Make screenshot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 15
  testRunner.Given("User type password \"72621010Abaccc\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 17
  testRunner.Given("Button \"Войти\" is Disabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 18
    testRunner.Given("Captcha appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 19
  testRunner.Given("Captcha submitted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 20
  testRunner.Given("User clicks on \"Войти\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 21
    testRunner.Given("Captcha appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 22
  testRunner.Given("Captcha submitted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 23
  testRunner.Then("Make screenshot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 24
     testRunner.Given("User type password \"72621010Abac\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 25
  testRunner.Given("User clicks on \"Войти\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 26
  testRunner.Given("User see Account Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Вход в систему. Обработка ошибок")]
        [NUnit.Framework.CategoryAttribute("135437")]
        public virtual void ВходВСистему_ОбработкаОшибок()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Вход в систему. Обработка ошибок", new string[] {
                        "135437"});
#line 30
  this.ScenarioSetup(scenarioInfo);
#line 32
  testRunner.Given("User goes to SignIn page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 33
  testRunner.Given("User signin \"Epayments\" with \"70008888888\" password \"72621010Abacc\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 34
  testRunner.Given("User gets \"Номер телефона / e-mail указан неверно\" message on SignIn form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 36
       testRunner.Given("User goes to SignIn page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 37
  testRunner.Given("User signin \"Epayments\" with \"70008888\" password \"72621010Abacc\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 38
  testRunner.Given("User gets \"Номер телефона / e-mail указан неверно\" message on SignIn form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 41
       testRunner.Given("User goes to SignIn page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 42
  testRunner.Given("User signin \"Epayments\" with \"7000888888801234\" password \"72621010Abacc\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 43
  testRunner.Given("User gets \"Номер телефона / e-mail указан неверно\" message on SignIn form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 45
         testRunner.Given("User goes to SignIn page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 46
  testRunner.Given("User signin \"Epayments\" with \"bizqa.swiftcom.uk\" password \"72621010Abacc\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 47
  testRunner.Given("User gets \"Номер телефона / e-mail указан неверно\" message on SignIn form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 49
           testRunner.Given("User goes to SignIn page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 50
  testRunner.Given("User signin \"Epayments\" with \"@qa.swiftcom.uk\" password \"72621010Abacc\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 51
  testRunner.Given("User gets \"Номер телефона / e-mail указан неверно\" message on SignIn form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 53
             testRunner.Given("User goes to SignIn page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 54
  testRunner.Given("User signin \"Epayments\" with \"biz@\" password \"72621010Abacc\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 55
  testRunner.Given("User gets \"Номер телефона / e-mail указан неверно\" message on SignIn form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Восстановление пароля")]
        [NUnit.Framework.CategoryAttribute("135438")]
        public virtual void ВосстановлениеПароля()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Восстановление пароля", new string[] {
                        "135438"});
#line 60
  this.ScenarioSetup(scenarioInfo);
#line 62
  testRunner.Given("User goes to SignIn page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 63
  testRunner.Given("User clicks on \"Забыли пароль?\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 64
  testRunner.Then("Redirected to /#/restorepassword", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 66
  testRunner.Given("User type login invalid@login.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 68
    testRunner.Given("Captcha appears on SignIn Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 69
  testRunner.Given("Captcha submitted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 70
  testRunner.Given("User clicks on \"Далее\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 71
  testRunner.Then("Validating message \"Пользователь не найден или не существует\" appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 72
  testRunner.Then("Make screenshot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 74
  testRunner.Then("User clears password login field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 75
  testRunner.Given("User type login +70066953484", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 76
    testRunner.Given("Captcha appears on SignIn Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 77
  testRunner.Given("Captcha submitted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 78
  testRunner.Given("Set StartTime for DB search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 79
  testRunner.Given("User clicks on \"Далее\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 80
  testRunner.Given("User fills new password", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperationType",
                        "Recipient"});
            table1.AddRow(new string[] {
                        "1",
                        "+70066953484"});
#line 81
  testRunner.Then("User gets VerificationCode in table \'ConfirmationCodes\' where:", ((string)(null)), table1, "Then ");
#line 84
  testRunner.Given("User fills ConfirmationCode for restoring password", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 85
  testRunner.Given("Set StartTime for DB search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 86
  testRunner.Given("User clicks on \"Прислать код повторно\" on restore password page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 88
  testRunner.Given("User clicks on \"Подтвердить\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 89
  testRunner.Then("Validating message \"Код введен неверно\" appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 90
  testRunner.Then("Make screenshot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 91
  testRunner.Then("User clears confirmation code field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperationType",
                        "Recipient"});
            table2.AddRow(new string[] {
                        "1",
                        "+70066953484"});
#line 93
  testRunner.Then("User gets VerificationCode in table \'ConfirmationCodes\' where:", ((string)(null)), table2, "Then ");
#line 96
  testRunner.Given("User fills ConfirmationCode for restoring password", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 97
  testRunner.Given("Set StartTime for DB search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 99
  testRunner.Given("User clicks on \"Подтвердить\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 100
  testRunner.Given("User see Account Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "MessageType",
                        "Priority",
                        "Receiver",
                        "Title"});
            table3.AddRow(new string[] {
                        "Email",
                        "3",
                        "db73f147ef8ff407309a8d0509.autotest@qa.swiftcom.uk",
                        "Изменение пароля"});
#line 102
  testRunner.Then("User selects records in table \'Notification\' for UserId=\"fb666660-1a9f-4b84-b35d-" +
                    "95771abec0d7\"", ((string)(null)), table3, "Then ");
#line 105
  testRunner.Given("User LogOut", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 106
  testRunner.Given("User signin \"Epayments\" with \"+70066953484\" restored password", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 107
  testRunner.Given("User see Account Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Вход в систему. Заморозка пользователя на 60мин")]
        [NUnit.Framework.CategoryAttribute("2712874")]
        [NUnit.Framework.CategoryAttribute("Unfreeze_user")]
        [NUnit.Framework.TestCaseAttribute("70dcac51-8f06-457e-95ec-2ee036702338", "0f7d264c08b5e939e6e6e38da2.autotest@qa.swiftcom.uk", "invalid", null)]
        public virtual void ВходВСистему_ЗаморозкаПользователяНа60Мин(string userId, string login, string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "2712874",
                    "Unfreeze_user"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Вход в систему. Заморозка пользователя на 60мин", @__tags);
#line 113
  this.ScenarioSetup(scenarioInfo);
#line 114
   testRunner.Given("User goes to SignIn page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 115
   testRunner.Given(string.Format("User signin \"Epayments\" with \"{0}\" password \"72621010Abac\"", login), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 116
  testRunner.Given("Captcha appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 117
  testRunner.Given("Captcha submitted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 118
  testRunner.Given("User clicks on \"Войти\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 119
  testRunner.Given("User see Account Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 120
  testRunner.Given("User LogOut", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 121
  testRunner.Given(string.Format("User signin \"Epayments\" with \"{0}\" password \"{1}\"", login, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 123
 testRunner.Given("User gets \"Неверный логин или пароль\" message on Landing SignIn form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 124
  testRunner.Given(string.Format("User type password \"{0}\"", password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 125
  testRunner.Given("User clicks on \"Войти\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 127
  testRunner.Given("User gets \"Неверный логин или пароль\" message on Landing SignIn form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 128
  testRunner.Given(string.Format("User type password \"{0}\"", password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 129
   testRunner.Given("Captcha appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 130
  testRunner.Given("Captcha submitted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 131
  testRunner.Given("User clicks on \"Войти\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 133
  testRunner.Given("User gets \"Неверный логин или пароль\" message on Landing SignIn form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 135
  testRunner.Given(string.Format("User type password \"{0}\"", password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 136
    testRunner.Given("Captcha appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 137
  testRunner.Given("Captcha submitted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 138
  testRunner.Given("User clicks on \"Войти\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 139
  testRunner.Given("User gets \"Неверный логин или пароль\" message on Landing SignIn form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 141
   testRunner.Given(string.Format("User type password \"{0}\"", password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 142
     testRunner.Given("Captcha appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 143
   testRunner.Given("Captcha submitted", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 145
    testRunner.Given("Set StartTime for DB search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 147
   testRunner.Given("User clicks on \"Войти\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 148
   testRunner.Given("User gets \"Неверный логин или пароль\" message on Landing SignIn form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 149
   testRunner.Given("User gets \"Счет будет разблокирован через: 00:59\" message on Landing SignIn form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 150
   testRunner.Then("Make screenshot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "MessageType",
                        "Priority",
                        "Receiver",
                        "Title"});
            table4.AddRow(new string[] {
                        "Email",
                        "2",
                        string.Format("{0}", login),
                        "Аккаунт временно заблокирован"});
#line 151
 testRunner.Then(string.Format("User selects records in table \'Notification\' for UserId=\"{0}\"", userId), ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Отслеживание UTM меток")]
        [NUnit.Framework.CategoryAttribute("455121")]
        public virtual void ОтслеживаниеUTMМеток()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Отслеживание UTM меток", new string[] {
                        "455121"});
#line 161
this.ScenarioSetup(scenarioInfo);
#line 162
 testRunner.Given("User open link \"https://www.sandbox.epayments.com/ru/?utm_source=3&utm_medium=1&u" +
                    "tm_campaign=wm5\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 163
 testRunner.Then("Cookie \"tags\" is not received", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 164
 testRunner.Given("User open link \"https://www.sandbox.epayments.com/?utm_source=3&utm_medium=1&utm_" +
                    "campaign=wm4\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 165
 testRunner.Then("User receive Cookie \"tags\" with value [{\"utm_source\": \"3\"}, {\"utm_term\": \"\"}, {\"u" +
                    "tm_medium\": \"1\"}, {\"utm_content\": \"\"}, {\"utm_campaign\": \"wm4\"}]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 166
 testRunner.Given("User goes to SignIn page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
