// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ePayments.Tests.Web.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("UserRegistration")]
    [NUnit.Framework.CategoryAttribute("UserRegistration")]
    public partial class UserRegistrationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "UserRegistration.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "UserRegistration", null, ProgrammingLanguage.CSharp, new string[] {
                        "UserRegistration"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Регистрация Individual User (по email)")]
        [NUnit.Framework.CategoryAttribute("135397")]
        public virtual void РегистрацияIndividualUserПоEmail()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Регистрация Individual User (по email)", new string[] {
                        "135397"});
#line 6
this.ScenarioSetup(scenarioInfo);
#line 10
  testRunner.Given("User goes to registration page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 11
   testRunner.Given("User clicks on button \"Продолжить\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 13
  testRunner.Then("\'Имя\' set FirstName to random text", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 14
  testRunner.Then("\'Фамилия\' set LastName to random text", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 15
     testRunner.Then("User change Country to Россия", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 16
  testRunner.Then("\'Электронная почта\' set to random email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
  testRunner.Then("\'Пароль\' set to \'72621010Abac\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 18
  testRunner.Then("\'Дата рождения\' set to \'01.01.1991\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 19
   testRunner.Given("Set StartTime for DB search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 21
 testRunner.Then("Select checkbox \'Я принимаю Правила и условия использования сервиса и Политику ко" +
                    "нфиденциальности\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 22
   testRunner.Given("User clicks on button \"Регистрация\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperationType",
                        "Recipient"});
            table1.AddRow(new string[] {
                        "33",
                        "email"});
#line 24
  testRunner.Then("User gets VerificationCode in table \'ConfirmationCodes\' by email:", ((string)(null)), table1, "Then ");
#line 27
  testRunner.Then("\'Ввести код вручную\' set confirmation code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 28
  testRunner.Given("User clicks on button \"Продолжить\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 30
  testRunner.Then("Verification widget appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 32
     testRunner.Then("No EPA cards section in menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 33
  testRunner.Then("No Affiliate Program section in menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "KYCId",
                        "UserRole",
                        "State",
                        "IsPep",
                        "PasswordExpireAt"});
            table2.AddRow(new string[] {
                        "1",
                        "185",
                        "Approved",
                        "0",
                        "*today+6month*"});
#line 34
  testRunner.Then("User selects records in \'Users\' for created user:", ((string)(null)), table2, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "MessageType",
                        "Priority",
                        "Receiver",
                        "Title"});
            table3.AddRow(new string[] {
                        "Email",
                        "3",
                        "**Receiver**",
                        "Изменение статуса аккаунта"});
            table3.AddRow(new string[] {
                        "Email",
                        "1",
                        "**Receiver**",
                        "Подтверждение e-mail"});
#line 38
  testRunner.Then("User selects records in table \'Notification\' for created user", ((string)(null)), table3, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "MobilePhone",
                        "FirstName",
                        "LastName",
                        "BirthDate",
                        "CitizenShipCountryId",
                        "ResidenceCountryId",
                        "Gender"});
            table4.AddRow(new string[] {
                        "**Email**",
                        "**MobilePhone**",
                        "**Generated**",
                        "**Generated**",
                        "01.01.1991",
                        "",
                        "185",
                        ""});
#line 43
 testRunner.Then("User selects records in \'PersonalData\' for created user:", ((string)(null)), table4, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "EpaId",
                        "ZendeskId",
                        "CreatedOn",
                        "UpdatedOn"});
            table5.AddRow(new string[] {
                        "<UserId>",
                        "**ID**",
                        "**today**",
                        ""});
#line 47
 testRunner.Then("User selects records in table \'EpaZendeskUser\' for created user:", ((string)(null)), table5, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Регистрация Business User")]
        [NUnit.Framework.CategoryAttribute("3674445")]
        public virtual void РегистрацияBusinessUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Регистрация Business User", new string[] {
                        "3674445"});
#line 54
this.ScenarioSetup(scenarioInfo);
#line 56
  testRunner.Given("User goes to registration page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 57
  testRunner.Given("User clicks on \"Бизнес аккаунт\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 58
  testRunner.Given("User clicks on button \"Продолжить\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 59
  testRunner.Given("Set StartTime for DB search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 61
  testRunner.Then("\'Электронная почта\' set to random email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 62
   testRunner.Given("User clicks on button \"Регистрация\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperationType",
                        "Recipient"});
            table6.AddRow(new string[] {
                        "8",
                        "**email**"});
#line 63
  testRunner.Then("User gets VerificationCode in table \'ConfirmationCodes\' by email:", ((string)(null)), table6, "Then ");
#line 67
 testRunner.Then("\'Пароль *\' set to \'72621010Abac\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 69
 testRunner.Then("\'Код подтверждения *\' set confirmation code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 71
 testRunner.Given("User clicks on button \"Продолжить\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 73
 testRunner.Then("User redirected to account page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 74
 testRunner.Then("No Affiliate Program section in menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "KYCId",
                        "UserRole",
                        "State",
                        "IsPep",
                        "PasswordExpireAt"});
            table7.AddRow(new string[] {
                        "0",
                        "60",
                        "Lead",
                        "0",
                        "9999-12-31"});
#line 75
 testRunner.Then("User selects records in \'Users\' for created user:", ((string)(null)), table7, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "CompanyName",
                        "WebSite",
                        "RegNumber",
                        "Country",
                        "TradingAddress"});
            table8.AddRow(new string[] {
                        "nikita company",
                        "https://www.nikitaivanov.com",
                        "9852108",
                        "Россия",
                        "USA,NY,Wall street 3"});
#line 78
 testRunner.Given("User fills User activation details for Business user:", ((string)(null)), table8, "Given ");
#line 81
 testRunner.Given("User clicks on \"Далее\" on Multiform", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 83
 testRunner.Then("\'Имя\' set FirstName to random text", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 84
 testRunner.Then("\'Фамилия\' set LastName to random text", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 85
 testRunner.Then("\'Страна проживания\' UI selector set to \'Россия\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 86
 testRunner.Then("\'Дата рождения\' set to \'01.01.1991\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 87
 testRunner.Then("\'Номер телефона\' set to random phone", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 88
 testRunner.Given("User clicks on \"Мужской\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 90
 testRunner.Given("Set StartTime for DB search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 92
 testRunner.Then("User set Country \"Россия\" in address of residence", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 93
 testRunner.Then("User sets State to Республика Татарстан", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 94
 testRunner.Then("User sets City to Казань", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 95
 testRunner.Then("User sets Postal Code to 424003", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 96
 testRunner.Then("User sets Address to Адресс", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 97
 testRunner.Then("Make screenshot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 99
 testRunner.Given("User clicks on \"Далее\" on Multiform", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperationType",
                        "Recipient"});
            table9.AddRow(new string[] {
                        "5",
                        "**Email**"});
#line 101
  testRunner.Then("User gets VerificationCode in table \'ConfirmationCodes\' by phone:", ((string)(null)), table9, "Then ");
#line 104
  testRunner.Given("User fills ConfirmationCode on activation details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 105
  testRunner.Given("User clicks on button \"Далее\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 107
   testRunner.Then("User gets message \"Спасибо за предоставление информации о компании. Для получения" +
                    " доступа до финансовых операций вам осталось подтвердить документами указанную и" +
                    "нформацию\" on Multiform", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 108
    testRunner.Given("User clicks on \"Закрыть\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "MessageType",
                        "Priority",
                        "Receiver",
                        "Title"});
            table10.AddRow(new string[] {
                        "Email",
                        "3",
                        "**Receiver**",
                        "Верификация аккаунта"});
            table10.AddRow(new string[] {
                        "Sms",
                        "1",
                        "**Receiver**",
                        "-"});
#line 110
  testRunner.Then("User selects records in table \'Notification\' for created user", ((string)(null)), table10, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "KYCId",
                        "UserRole",
                        "State",
                        "IsPep",
                        "PasswordExpireAt"});
            table11.AddRow(new string[] {
                        "1",
                        "60",
                        "WaitingManualRegistration",
                        "0",
                        "9999-12-31"});
#line 114
  testRunner.Then("User selects records in \'Users\' for created user:", ((string)(null)), table11, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "MobilePhone",
                        "FirstName",
                        "LastName",
                        "BirthDate",
                        "CitizenShipCountryId",
                        "ResidenceCountryId",
                        "Gender"});
            table12.AddRow(new string[] {
                        "**Email**",
                        "**MobilePhone**",
                        "**Generated**",
                        "**Generated**",
                        "01.01.1991",
                        "",
                        "185",
                        "Male"});
#line 117
 testRunner.Then("User selects records in \'PersonalData\' for created user:", ((string)(null)), table12, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "EpaId",
                        "ZendeskId",
                        "CreatedOn",
                        "UpdatedOn"});
            table13.AddRow(new string[] {
                        "<UserId>",
                        "**ID**",
                        "**today**",
                        "**today**"});
#line 120
 testRunner.Then("User selects records in table \'EpaZendeskUser\' for created business user:", ((string)(null)), table13, "Then ");
#line 125
 testRunner.Then("Modal window \'needAgreeMemberTerms\' is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 127
 testRunner.Then("Click on Согласен(-а) on Modal Window", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 129
 testRunner.Then("User clicks on Верифицировать счет on Menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Citizenship",
                        "DocumentNumber",
                        "ValidUntil",
                        "DocumentUpload"});
            table14.AddRow(new string[] {
                        "Россия",
                        "12312 43",
                        "01.01.2099",
                        "3.jpg"});
#line 130
 testRunner.Then("User confirms Identity", ((string)(null)), table14, "Then ");
#line 134
 testRunner.Then("User confirms Company details with document 3.jpg", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 135
 testRunner.Then("User clicks on Верифицировать счет on Menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 136
 testRunner.Then("User confirms Address \"Россия, Республика Татарстан, 424003, Казань, Адресс\" with" +
                    " document 3.jpg", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 137
 testRunner.Then("User fill Financial activity questionnaire", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 138
 testRunner.Given("User clicks on \"Закрыть\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 139
 testRunner.Then("User send verification request", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 140
 testRunner.Then("User gets message \"Заявка на рассмотрении\" on Multiform", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 141
 testRunner.Then("Operator marks business user with RiskLevel A", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 142
 testRunner.Then("Operator set created user as verified", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 143
 testRunner.Given("User clicks on \"Закрыть\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 144
 testRunner.Then("User refresh the page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "KYCId",
                        "UserRole",
                        "State",
                        "IsPep",
                        "PasswordExpireAt"});
            table15.AddRow(new string[] {
                        "2",
                        "61",
                        "Approved",
                        "0",
                        "9999-12-31"});
#line 145
 testRunner.Then("User selects records in \'Users\' for created user:", ((string)(null)), table15, "Then ");
#line 148
 testRunner.Given("User clicks on Партнерская программа menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "LinkNames",
                        "Transitions",
                        "Registrations",
                        "ForPayment",
                        "Processing",
                        "Cancelled"});
            table16.AddRow(new string[] {
                        "**link**",
                        "0",
                        "0",
                        "~ 0.00 $",
                        "~ 0.00 $",
                        "~ 0.00 $"});
#line 149
 testRunner.Given("User see partner links:", ((string)(null)), table16, "Given ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Регистрация по партнерской ссылке (физик)")]
        [NUnit.Framework.CategoryAttribute("1674898")]
        public virtual void РегистрацияПоПартнерскойСсылкеФизик()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Регистрация по партнерской ссылке (физик)", new string[] {
                        "1674898"});
#line 155
this.ScenarioSetup(scenarioInfo);
#line 156
 testRunner.Given("User goes to SignIn page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 157
 testRunner.Given("User signin \"Epayments\" with \"a72f1644eabcf2a7fe28f9987e.autotest@qa.swiftcom.uk\"" +
                    " password \"72621010Abac\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 158
 testRunner.Given("User clicks on Партнерская программа menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 159
 testRunner.Given("Memorize partner link table with 2 links", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 160
 testRunner.Given("User LogOut", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 162
 testRunner.Given("User open partner\'s link \"https://sandbox.epacash.com/hidvltu1f8\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 163
 testRunner.Then("User receive Cookie \"iv\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 164
 testRunner.Then("User receive Cookie \"promocode\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 165
 testRunner.Then("User receive Cookie \"tags\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 166
 testRunner.Given("User goes to registration page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 168
   testRunner.Given("User clicks on button \"Продолжить\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 169
 testRunner.Then("Checkbox \"Есть промокод?\" is checked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 170
  testRunner.Then("\'Промокод\' value is \'hidvltu1f8\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 171
   testRunner.Then("Text \"Регистрация по промо-коду:\" appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 172
   testRunner.Then("Text \"hidvltu1f8\" appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 174
  testRunner.Then("\'Имя\' set FirstName to random text", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 175
  testRunner.Then("\'Фамилия\' set LastName to random text", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 176
     testRunner.Then("User change Country to Россия", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 177
  testRunner.Then("\'Электронная почта\' set to random email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 178
  testRunner.Then("\'Пароль\' set to \'72621010Abac\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 179
  testRunner.Then("\'Дата рождения\' set to \'01.01.1991\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 182
   testRunner.Given("Set StartTime for DB search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 184
 testRunner.Then("Select checkbox \'Я принимаю Правила и условия использования сервиса и Политику ко" +
                    "нфиденциальности\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 185
   testRunner.Given("User clicks on button \"Регистрация\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperationType",
                        "Recipient"});
            table17.AddRow(new string[] {
                        "33",
                        "email"});
#line 187
  testRunner.Then("User gets VerificationCode in table \'ConfirmationCodes\' by email:", ((string)(null)), table17, "Then ");
#line 190
  testRunner.Then("\'Ввести код вручную\' set confirmation code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 191
  testRunner.Given("User clicks on button \"Продолжить\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 193
  testRunner.Then("Verification widget appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "KYCId",
                        "UserRole",
                        "State",
                        "IsPep",
                        "PasswordExpireAt"});
            table18.AddRow(new string[] {
                        "1",
                        "185",
                        "Approved",
                        "0",
                        "*today+6month*"});
#line 195
 testRunner.Then("User selects records in \'Users\' for created user:", ((string)(null)), table18, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "MobilePhone",
                        "FirstName",
                        "LastName",
                        "BirthDate",
                        "CitizenShipCountryId",
                        "ResidenceCountryId",
                        "Gender"});
            table19.AddRow(new string[] {
                        "**Email**",
                        "**MobilePhone**",
                        "**Generated**",
                        "**Generated**",
                        "01.01.1991",
                        "",
                        "185",
                        ""});
#line 200
 testRunner.Then("User selects records in \'PersonalData\' for created user:", ((string)(null)), table19, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "EpaId",
                        "ZendeskId",
                        "CreatedOn",
                        "UpdatedOn"});
            table20.AddRow(new string[] {
                        "<UserId>",
                        "**ID**",
                        "**today**",
                        ""});
#line 203
 testRunner.Then("User selects records in table \'EpaZendeskUser\' for created user:", ((string)(null)), table20, "Then ");
#line 207
     testRunner.Then("No EPA cards section in menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 208
  testRunner.Then("No Affiliate Program section in menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 210
 testRunner.Given("User LogOut", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 212
 testRunner.Given("User signin \"Epayments\" with \"a72f1644eabcf2a7fe28f9987e.autotest@qa.swiftcom.uk\"" +
                    " password \"72621010Abac\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 213
 testRunner.Given("User clicks on Партнерская программа menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "LinkNames",
                        "Transitions",
                        "Registrations",
                        "ForPayment",
                        "Processing",
                        "Cancelled"});
            table21.AddRow(new string[] {
                        "000-255206",
                        "0",
                        "0",
                        "~ 0.00 $",
                        "~ 0.00 $",
                        "~ 0.00 $"});
            table21.AddRow(new string[] {
                        "hidvltu1f8",
                        "+1",
                        "+1",
                        "~ 0.00 $",
                        "~ 0.00 $",
                        "~ 0.00 $"});
#line 214
 testRunner.Given("User see partner links with updated columns:", ((string)(null)), table21, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "BonusRefOwnerId",
                        "IsActive",
                        "UtmSource",
                        "UtmMedium",
                        "UtmTerm",
                        "UtmContent",
                        "UtmCampaign",
                        "LinkType",
                        "Link"});
            table22.AddRow(new string[] {
                        "",
                        "true",
                        "-",
                        "-",
                        "-",
                        "-",
                        "-",
                        "AffilateLink",
                        "hidvltu1f8"});
#line 218
 testRunner.Then("User selects records in table \'BonusProgramClients\' for created user:", ((string)(null)), table22, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Регистрация по бонусной ссылке (физик)")]
        [NUnit.Framework.CategoryAttribute("135400")]
        public virtual void РегистрацияПоБонуснойСсылкеФизик()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Регистрация по бонусной ссылке (физик)", new string[] {
                        "135400"});
#line 225
this.ScenarioSetup(scenarioInfo);
#line 227
 testRunner.Given("User goes to SignIn page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 228
 testRunner.Given("User signin \"Epayments\" with \"a72f1644eabcf2a7fe28f9987e.autotest@qa.swiftcom.uk\"" +
                    " password \"72621010Abac\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 229
 testRunner.Given("User clicks on Партнерская программа menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 230
 testRunner.Given("Memorize partner link table with 2 links", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 231
 testRunner.Given("User LogOut", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 232
 testRunner.Given("User open partner\'s link \"http://r.sandbox.epayments.com/?promo=000-255206\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 233
 testRunner.Then("User receive Cookie \"referenceId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 234
 testRunner.Then("User receive Cookie \"tags\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 235
 testRunner.Then("User receive Cookie \"iv\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 236
 testRunner.Then("User receive Cookie \"promocode\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 237
  testRunner.Given("User clicks on \"Войти\" on Landing Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 239
  testRunner.Given("User goes to registration page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 241
   testRunner.Given("User clicks on button \"Продолжить\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 242
 testRunner.Then("Checkbox \"Есть промокод?\" is checked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 243
  testRunner.Then("\'Промокод\' value is \'000-255206\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 244
   testRunner.Then("Text \"Регистрация по промо-коду:\" appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 245
   testRunner.Then("Text \"000-255206\" appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 247
  testRunner.Then("\'Имя\' set FirstName to random text", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 248
  testRunner.Then("\'Фамилия\' set LastName to random text", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 249
     testRunner.Then("User change Country to Россия", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 250
  testRunner.Then("\'Электронная почта\' set to random email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 251
  testRunner.Then("\'Пароль\' set to \'72621010Abac\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 252
  testRunner.Then("\'Дата рождения\' set to \'01.01.1991\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 255
   testRunner.Given("Set StartTime for DB search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 257
     testRunner.Then("User scrolls down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 258
  testRunner.Then("Select checkbox \'Я принимаю Правила и условия использования сервиса и Политику ко" +
                    "нфиденциальности\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 259
  testRunner.Given("User clicks on button \"Регистрация\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperationType",
                        "Recipient"});
            table23.AddRow(new string[] {
                        "33",
                        "email"});
#line 261
  testRunner.Then("User gets VerificationCode in table \'ConfirmationCodes\' by email:", ((string)(null)), table23, "Then ");
#line 265
  testRunner.Then("\'Ввести код вручную\' set confirmation code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 266
  testRunner.Given("User clicks on button \"Продолжить\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 268
   testRunner.Then("Verification widget appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "KYCId",
                        "UserRole",
                        "State",
                        "IsPep",
                        "PasswordExpireAt"});
            table24.AddRow(new string[] {
                        "1",
                        "185",
                        "Approved",
                        "0",
                        "9999-12-31"});
#line 270
  testRunner.Then("User selects records in \'Users\' for created user:", ((string)(null)), table24, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "MessageType",
                        "Priority",
                        "Receiver",
                        "Title"});
            table25.AddRow(new string[] {
                        "Email",
                        "3",
                        "**Receiver**",
                        "Изменение статуса аккаунта"});
            table25.AddRow(new string[] {
                        "Email",
                        "1",
                        "**Receiver**",
                        "Подтверждение e-mail"});
#line 274
  testRunner.Then("User selects records in table \'Notification\' for created user", ((string)(null)), table25, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "MobilePhone",
                        "FirstName",
                        "LastName",
                        "BirthDate",
                        "CitizenShipCountryId",
                        "ResidenceCountryId",
                        "Gender"});
            table26.AddRow(new string[] {
                        "**Email**",
                        "**MobilePhone**",
                        "**Generated**",
                        "**Generated**",
                        "01.01.1991",
                        "",
                        "185",
                        ""});
#line 279
  testRunner.Then("User selects records in \'PersonalData\' for created user:", ((string)(null)), table26, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "EpaId",
                        "ZendeskId",
                        "CreatedOn",
                        "UpdatedOn"});
            table27.AddRow(new string[] {
                        "<UserId>",
                        "**ID**",
                        "**today**",
                        ""});
#line 282
 testRunner.Then("User selects records in table \'EpaZendeskUser\' for created user:", ((string)(null)), table27, "Then ");
#line 286
     testRunner.Then("No EPA cards section in menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 287
  testRunner.Then("No Affiliate Program section in menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 289
 testRunner.Given("User LogOut", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 290
 testRunner.Given("User signin \"Epayments\" with \"a72f1644eabcf2a7fe28f9987e.autotest@qa.swiftcom.uk\"" +
                    " password \"72621010Abac\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 291
 testRunner.Given("User clicks on Партнерская программа menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "LinkNames",
                        "Transitions",
                        "Registrations",
                        "ForPayment",
                        "Processing",
                        "Cancelled"});
            table28.AddRow(new string[] {
                        "000-255206",
                        "+1",
                        "+1",
                        "~ 0.00 $",
                        "~ 0.00 $",
                        "~ 0.00 $"});
            table28.AddRow(new string[] {
                        "hidvltu1f8",
                        "0",
                        "0",
                        "~ 0.00 $",
                        "~ 0.00 $",
                        "~ 0.00 $"});
#line 292
 testRunner.Given("User see partner links with updated columns:", ((string)(null)), table28, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "BonusRefOwnerId",
                        "IsActive",
                        "UtmSource",
                        "UtmMedium",
                        "UtmTerm",
                        "UtmContent",
                        "UtmCampaign",
                        "LinkType",
                        "Link"});
            table29.AddRow(new string[] {
                        "65B6AFB7-C21F-45A5-853B-45C2DA9D8A44",
                        "true",
                        "-",
                        "-",
                        "-",
                        "-",
                        "-",
                        "Bonus",
                        "000-255206"});
#line 296
 testRunner.Then("User selects records in table \'BonusProgramClients\' for created user:", ((string)(null)), table29, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Регистрация по бонусной ссылке c UTM метками(физик)")]
        [NUnit.Framework.CategoryAttribute("2712877")]
        public virtual void РегистрацияПоБонуснойСсылкеCUTMМеткамиФизик()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Регистрация по бонусной ссылке c UTM метками(физик)", new string[] {
                        "2712877"});
#line 302
this.ScenarioSetup(scenarioInfo);
#line 303
 testRunner.Given("User goes to SignIn page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 304
 testRunner.Given("User signin \"Epayments\" with \"a72f1644eabcf2a7fe28f9987e.autotest@qa.swiftcom.uk\"" +
                    " password \"72621010Abac\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 305
 testRunner.Given("User clicks on Партнерская программа menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 306
 testRunner.Given("Memorize partner link table with 2 links", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 307
 testRunner.Given("User LogOut", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 308
 testRunner.Given("User open partner\'s link \"http://r.sandbox.epayments.com/?promo=000-255206&utm_me" +
                    "dium=[wrrwrw]&utm_source=[fhghghgf]&utm_campaign=[gfhghjhgjgh]&utm_term=[ghjghj]" +
                    "&utm_content=[ghjhgjghj]\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 309
 testRunner.Then("User receive Cookie \"referenceId\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 310
 testRunner.Then("User receive Cookie \"tags\" with value [{\"utm_source\": \"%5bfhghghgf%5d\"}, {\"utm_te" +
                    "rm\": \"%5bghjghj%5d\"}, {\"utm_medium\": \"%5bwrrwrw%5d\"}, {\"utm_content\": \"%5bghjhgj" +
                    "ghj%5d\"}, {\"utm_campaign\": \"%5bgfhghjhgjgh%5d\"}]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 311
 testRunner.Then("User receive Cookie \"iv\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 312
 testRunner.Then("User receive Cookie \"promocode\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 313
  testRunner.Given("User clicks on \"Войти\" on Landing Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 314
  testRunner.Given("User goes to registration page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 316
 testRunner.Given("User clicks on button \"Продолжить\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 317
 testRunner.Then("Checkbox \"Есть промокод?\" is checked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 318
 testRunner.Then("\'Промокод\' value is \'000-255206\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 319
 testRunner.Then("Text \"Регистрация по промо-коду:\" appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 320
 testRunner.Then("Text \"000-255206\" appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 322
  testRunner.Then("\'Имя\' set FirstName to random text", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 323
  testRunner.Then("\'Фамилия\' set LastName to random text", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 324
     testRunner.Then("User change Country to Россия", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 325
  testRunner.Then("\'Электронная почта\' set to random email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 326
  testRunner.Then("\'Пароль\' set to \'72621010Abac\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 327
  testRunner.Then("\'Дата рождения\' set to \'01.01.1991\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 330
   testRunner.Given("Set StartTime for DB search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 332
 testRunner.Then("Select checkbox \'Я принимаю Правила и условия использования сервиса и Политику ко" +
                    "нфиденциальности\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 333
 testRunner.Given("User clicks on button \"Регистрация\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperationType",
                        "Recipient"});
            table30.AddRow(new string[] {
                        "33",
                        "email"});
#line 335
  testRunner.Then("User gets VerificationCode in table \'ConfirmationCodes\' by email:", ((string)(null)), table30, "Then ");
#line 338
  testRunner.Then("\'Ввести код вручную\' set confirmation code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 339
   testRunner.Given("Set StartTime for DB search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 341
  testRunner.Given("User clicks on button \"Продолжить\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 343
  testRunner.Then("Verification widget appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "KYCId",
                        "UserRole",
                        "State",
                        "IsPep",
                        "PasswordExpireAt"});
            table31.AddRow(new string[] {
                        "1",
                        "185",
                        "Approved",
                        "0",
                        "9999-12-31"});
#line 345
 testRunner.Then("User selects records in \'Users\' for created user:", ((string)(null)), table31, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "MessageType",
                        "Priority",
                        "Receiver",
                        "Title"});
            table32.AddRow(new string[] {
                        "Email",
                        "3",
                        "**Receiver**",
                        "Изменение статуса аккаунта"});
#line 350
  testRunner.Then("User selects records in table \'Notification\' for created user", ((string)(null)), table32, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "KYCId",
                        "UserRole",
                        "State",
                        "IsPep",
                        "PasswordExpireAt"});
            table33.AddRow(new string[] {
                        "1",
                        "185",
                        "Approved",
                        "0",
                        "9999-12-31"});
#line 354
 testRunner.Then("User selects records in \'Users\' for created user:", ((string)(null)), table33, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "MobilePhone",
                        "FirstName",
                        "LastName",
                        "BirthDate",
                        "CitizenShipCountryId",
                        "ResidenceCountryId",
                        "Gender"});
            table34.AddRow(new string[] {
                        "**Email**",
                        "**MobilePhone**",
                        "**Generated**",
                        "**Generated**",
                        "01.01.1991",
                        "",
                        "185",
                        ""});
#line 357
 testRunner.Then("User selects records in \'PersonalData\' for created user:", ((string)(null)), table34, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "EpaId",
                        "ZendeskId",
                        "CreatedOn",
                        "UpdatedOn"});
            table35.AddRow(new string[] {
                        "<UserId>",
                        "**ID**",
                        "**today**",
                        ""});
#line 360
 testRunner.Then("User selects records in table \'EpaZendeskUser\' for created user:", ((string)(null)), table35, "Then ");
#line 364
     testRunner.Then("No EPA cards section in menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 365
  testRunner.Then("No Affiliate Program section in menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 367
 testRunner.Given("User LogOut", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 368
 testRunner.Given("User signin \"Epayments\" with \"a72f1644eabcf2a7fe28f9987e.autotest@qa.swiftcom.uk\"" +
                    " password \"72621010Abac\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 369
 testRunner.Given("User clicks on Партнерская программа menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "LinkNames",
                        "Transitions",
                        "Registrations",
                        "ForPayment",
                        "Processing",
                        "Cancelled"});
            table36.AddRow(new string[] {
                        "000-255206",
                        "+1",
                        "+1",
                        "~ 0.00 $",
                        "~ 0.00 $",
                        "~ 0.00 $"});
            table36.AddRow(new string[] {
                        "hidvltu1f8",
                        "0",
                        "0",
                        "~ 0.00 $",
                        "~ 0.00 $",
                        "~ 0.00 $"});
#line 370
 testRunner.Given("User see partner links with updated columns:", ((string)(null)), table36, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "BonusRefOwnerId",
                        "IsActive",
                        "UtmSource",
                        "UtmMedium",
                        "UtmTerm",
                        "UtmContent",
                        "UtmCampaign",
                        "LinkType",
                        "Link"});
            table37.AddRow(new string[] {
                        "65B6AFB7-C21F-45A5-853B-45C2DA9D8A44",
                        "true",
                        "[fhghghgf]",
                        "[wrrwrw]",
                        "[ghjghj]",
                        "[ghjhgjghj]",
                        "[gfhghjhgjgh]",
                        "Bonus",
                        "000-255206"});
#line 374
 testRunner.Then("User selects records in table \'BonusProgramClients\' for created user:", ((string)(null)), table37, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Регистрация с попаданием на санкции - физ лицо")]
        [NUnit.Framework.TestCaseAttribute("true", "Confirmed", "5", "Blocked", "63", new string[] {
                "433742",
                "Reset_first_name"}, Category="433742,Reset_first_name")]
        [NUnit.Framework.TestCaseAttribute("false", "Not sanctioned", "2", "Approved", "62", new string[] {
                "2951621",
                "Reset_first_name"}, Category="2951621,Reset_first_name")]
        public virtual void РегистрацияСПопаданиемНаСанкции_ФизЛицо(string isSanctioned, string status, string kYCId, string state, string userRole, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Регистрация с попаданием на санкции - физ лицо", exampleTags);
#line 380
this.ScenarioSetup(scenarioInfo);
#line 382
 testRunner.Given("User goes to registration page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 384
 testRunner.Given("User clicks on button \"Продолжить\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 385
 testRunner.Then("Checkbox \"Есть промокод?\" is unchecked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 387
 testRunner.Then("\'Имя\' set to \'ALEXEY\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 388
 testRunner.Then("\'Фамилия\' set to \'MILCHAKOV\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 389
 testRunner.Then("User change Country to Украина", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 390
 testRunner.Then("\'Электронная почта\' set to random email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 391
 testRunner.Then("\'Пароль\' set to \'72621010Abac\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 392
 testRunner.Then("\'Дата рождения\' set to \'30.04.1991\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 393
 testRunner.Given("Set StartTime for DB search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 394
 testRunner.Then("Select checkbox \'Я принимаю Правила и условия использования сервиса и Политику ко" +
                    "нфиденциальности\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 395
 testRunner.Given("User clicks on button \"Регистрация\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperationType",
                        "Recipient"});
            table38.AddRow(new string[] {
                        "33",
                        "email"});
#line 396
 testRunner.Then("User gets VerificationCode in table \'ConfirmationCodes\' by email:", ((string)(null)), table38, "Then ");
#line 400
  testRunner.Then("\'Ввести код вручную\' set confirmation code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 401
  testRunner.Given("User clicks on button \"Продолжить\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 403
  testRunner.Then("Verification widget appears", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 406
     testRunner.Then("No EPA cards section in menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 408
 testRunner.Then("No records in \'SanctionCheck\' for created user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "KYCId",
                        "UserRole",
                        "State",
                        "IsPep",
                        "PasswordExpireAt"});
            table39.AddRow(new string[] {
                        "1",
                        "185",
                        "Approved",
                        "0",
                        "*today+6month*"});
#line 409
  testRunner.Then("User selects records in \'Users\' for created user:", ((string)(null)), table39, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "MessageType",
                        "Priority",
                        "Receiver",
                        "Title"});
            table40.AddRow(new string[] {
                        "Email",
                        "3",
                        "**Email**",
                        "Изменение статуса аккаунта"});
            table40.AddRow(new string[] {
                        "Email",
                        "1",
                        "**Email**",
                        "Подтверждение e-mail"});
#line 413
  testRunner.Then("User selects records in table \'Notification\' for created user", ((string)(null)), table40, "Then ");
#line 419
 testRunner.Then("Make screenshot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 421
  testRunner.Given("Set StartTime for DB search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 423
 testRunner.Then("User clicks on \'Через личный кабинет\' on VerificationWidget", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 424
 testRunner.Then("\'Номер телефона:\' set to random phone", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 425
 testRunner.Given("User clicks on \"Отправить SMS\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                        "OperationType",
                        "Recipient"});
            table41.AddRow(new string[] {
                        "5",
                        "**Phone**"});
#line 426
 testRunner.Then("User gets VerificationCode in table \'ConfirmationCodes\' by phone:", ((string)(null)), table41, "Then ");
#line 431
 testRunner.Then("\'Код из SMS:\' set confirmation code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 432
 testRunner.Given("User clicks on \"Продолжить\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 434
  testRunner.Then("Verification widget contains \'Подтвердите вашу личность\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 435
 testRunner.Then("\'Гражданство:\' citizenship set to \'Россия\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 436
 testRunner.Given("User clicks on \"Общегражданский паспорт\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 437
 testRunner.Then("\'Серия и номер документа:\' set to \'8811073131\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 438
 testRunner.Then("User scrolls down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 440
 testRunner.Then("File \"passport.jpg\" uploaded for verification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 441
 testRunner.Then("Make screenshot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 442
 testRunner.Given("User clicks on \"Продолжить\" on verification widget", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 444
 testRunner.Then("Verification widget contains \'Укажите адрес проживания\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 445
 testRunner.Then("\'Округ/Область:\' set to \'state/district\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 446
 testRunner.Then("\'Город:\' set to \'city\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 447
 testRunner.Then("\'Индекс:\' set to \'123456\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 448
 testRunner.Then("\'Адрес:\' details set to \'adress\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 449
 testRunner.Then("Make screenshot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 451
 testRunner.Given("User clicks on \"Продолжить\" on verification widget", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 452
 testRunner.Then("User scrolls down", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 454
 testRunner.Then("Set select option to \'Cтраница паспорта с адресом регистрации\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 455
 testRunner.Then("File \"3.jpg\" uploaded for verification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 456
 testRunner.Then("Make screenshot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 457
 testRunner.Given("User clicks on \"Отправить заявку\" on verification widget", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 459
 testRunner.Then("Verification widget contains \'Заявка на верификацию принята\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 460
 testRunner.Then("Operator marks business user with RiskLevel A", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 461
 testRunner.Then("Operator try to set created user as verified", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 462
  testRunner.Then("Make screenshot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                        "Scenario",
                        "Status",
                        "IsConfirmedPep"});
            table42.AddRow(new string[] {
                        "BeforeVerification",
                        "InProcess",
                        "false"});
#line 464
 testRunner.Then("User selects record in \'SanctionCheck\' for created user:", ((string)(null)), table42, "Then ");
#line 468
 testRunner.Then(string.Format("Send CA {0} positive callback for created user", isSanctioned), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                        "Scenario",
                        "Status",
                        "IsConfirmedPep"});
            table43.AddRow(new string[] {
                        "BeforeVerification",
                        string.Format("{0}", status),
                        "false"});
#line 469
 testRunner.Then("User selects record in \'SanctionCheck\' for created user:", ((string)(null)), table43, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                        "KYCId",
                        "UserRole",
                        "State",
                        "IsPep",
                        "PasswordExpireAt"});
            table44.AddRow(new string[] {
                        string.Format("{0}", kYCId),
                        string.Format("{0}", userRole),
                        string.Format("{0}", state),
                        "0",
                        "9999-12-31"});
#line 473
 testRunner.Then("User selects records in \'Users\' for created user:", ((string)(null)), table44, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
